default:
  models:
    Section: read
    Page: read
    Site: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Section: manage
    Page: manage
    Site: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage
