# This workflow will run whenever a PR is opened or changed.
#
# It will run tests and a few safety checks.
#
# If everything passes it can be set to auto-deploy to your staging app on Heroku.
#
# This workflow is primarily meant to be triggered automatically, but it can be run manually.
name: " ğŸš… _ BT - Internal CI"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]

jobs:
  super_scaffolding:
    # This makes it so that this job only runs in the starter repo itself, and not in
    # applications started from the starter repo. If you want to run super scaffolding
    # test for your own app you can remove or comment out this next line.
    if: github.repository == 'bullet-train-co/bullet_train'
    name: ğŸ—ï¸ Super Scaffolding Tests
    uses: ./.github/workflows/_run_super_scaffolding_tests.yml
    secrets: inherit
  core_minitest:
    # This makes it so that this job only runs in the starter repo itself, and not in
    # applications started from the starter repo. If you want to run super scaffolding
    # test for your own app you can remove or comment out this next line.
    if: github.repository == 'bullet-train-co/bullet_train'
    name: "ğŸ§ª Core: Minitest"
    uses: ./.github/workflows/_run_tests.yml
    secrets: inherit
    with:
      use-core-repo: true
  core_super_scaffolding:
    # This makes it so that this job only runs in the starter repo itself, and not in
    # applications started from the starter repo. If you want to run super scaffolding
    # test for your own app you can remove or comment out this next line.
    if: github.repository == 'bullet-train-co/bullet_train'
    name: "ğŸ—ï¸ Core: Super Scaffolding Tests"
    uses: ./.github/workflows/_run_super_scaffolding_tests.yml
    secrets: inherit
    with:
      use-core-repo: true
